config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :sales
  resources :leads
  resources :vehicles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :company
  has_many :sales, dependent: :destroy
  has_many :vehicles, through: :sales
  validates :name, :phone, :email, presence: true
  validates_uniqueness_of :name, scope: [:phone, :email]
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: %i[ show edit update destroy ]

  # GET /leads or /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1 or /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads or /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to lead_url(@lead), notice: "Lead was successfully created." }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1 or /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to lead_url(@lead), notice: "Lead was successfully updated." }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1 or /leads/1.json
  def destroy
    @lead.destroy

    respond_to do |format|
      format.html { redirect_to leads_url, notice: "Lead was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lead_params
      params.require(:lead).permit(:name, :phone, :email)
    end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_form.html.erb
<%= form_with(model: lead) do |form| %>
  <% if lead.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
        <% lead.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/leads/_lead.html.erb
<div id="<%= dom_id lead %>">
  <p>
    <strong>Name:</strong>
    <%= lead.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= lead.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= lead.email %>
  </p>

</div>

app/views/leads/edit.html.erb
<h1>Editing lead</h1>

<%= render "form", lead: @lead %>

<br>

<div>
  <%= link_to "Show this lead", @lead %> |
  <%= link_to "Back to leads", leads_path %>
</div>

app/views/leads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Leads</h1>

<div id="leads">
  <% @leads.each do |lead| %>
    <%= render lead %>
    <p>
      <%= link_to "Show this lead", lead %>
    </p>
  <% end %>
</div>

<%= link_to "New lead", new_lead_path %>

app/views/leads/new.html.erb
<h1>New lead</h1>

<%= render "form", lead: @lead %>

<br>

<div>
  <%= link_to "Back to leads", leads_path %>
</div>

app/views/leads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lead %>

<div>
  <%= link_to "Edit this lead", edit_lead_path(@lead) %> |
  <%= link_to "Back to leads", leads_path %>

  <%= button_to "Destroy this lead", @lead, method: :delete %>
</div>