config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :sales
  resources :leads
  resources :vehicles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :vehicle
  belongs_to :lead
  has_one :company, through: :lead
  validates :vehicle_id, :lead_id, presence: true
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:amount, :vehicle_id, :lead_id)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale) do |form| %>
  <% if sale.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :vehicle_id, style: "display: block" %>
    <%= form.text_field :vehicle_id %>
  </div>

  <div>
    <%= form.label :lead_id, style: "display: block" %>
    <%= form.text_field :lead_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/_sale.html.erb
<div id="<%= dom_id sale %>">
  <p>
    <strong>Amount:</strong>
    <%= sale.amount %>
  </p>

  <p>
    <strong>Vehicle:</strong>
    <%= sale.vehicle_id %>
  </p>

  <p>
    <strong>Lead:</strong>
    <%= sale.lead_id %>
  </p>

</div>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Show this sale", @sale %> |
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sales</h1>

<div id="sales">
  <% @sales.each do |sale| %>
    <%= render sale %>
    <p>
      <%= link_to "Show this sale", sale %>
    </p>
  <% end %>
</div>

<%= link_to "New sale", new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sale %>

<div>
  <%= link_to "Edit this sale", edit_sale_path(@sale) %> |
  <%= link_to "Back to sales", sales_path %>

  <%= button_to "Destroy this sale", @sale, method: :delete %>
</div>